apiVersion: v1
kind: Service
metadata:
  name: {{ include "products.fullname" . }}
  labels:
  {{- include "products.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8000
      protocol: TCP
      name: web
    - port: 8081
      targetPort: 8081
      protocol: TCP
      name: manager
  selector:
  {{- include "products.selectorLabels" . | nindent 4 }}
